name: Linux Build

on:  
  push:
  workflow_dispatch:
  
jobs:
  build:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      # - name: Check out repo
      #   uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get install curl jq -y

      - name: Obtain last commit
        run: |
          LAST_COMMIT=$(curl -s -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/cosmos/gaia/branches/release/v9.0.x | jq -r '.commit.sha')
          echo $LAST_COMMIT > ~/.last_commit

      - name: Setup environment
        run: |
          sudo apt install build-essential wget -y

      - name: Install golang
        run: |
          wget https://go.dev/dl/go1.18.5.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.18.5.linux-amd64.tar.gz

      - name: Clone and build Gaia
        run: |
          export PATH=$PATH:/usr/local/go/bin
          git clone https://github.com/cosmos/gaia.git
          cd gaia
          git checkout release/v9.0.x
          make build
          cp build/gaiad ~/gaiad-linux-nightly
      
      - name: Print gaia version
        run: |
          ~/gaiad-linux-nightly version
          
      # - name: Upload assets
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: gaia-linux-ubuntu-latest
      #     path: ./gaia/build/

      # Publishing the release
      - name: Remove old releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 0
          delete_tag_pattern: "linux"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "~/gaiad-linux-nightly"
          name: "Snapshots for Linux"
          bodyFile: .github/workflows/linux_release_body.md
          prerelease: true
          replacesArtifacts: false
          allowUpdates: false
          tag: linux
          token: ${{ secrets.GITHUB_TOKEN }}