---
name: Triggered Workflow
on:
  repository_dispatch:
    types: [remote_trigger]
jobs:
  triggered:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow was triggered
        run: echo "Hi!"